### ISSUE TITLE
Add support for Autoptimize

### ISSUE THREAD

**Issue by Remzi1993** [Remzi1993/wp-jquery-manager#16]
I should add support for Autoptimize, so that users don't need to set up anything.
Mentioning @futtta Frank is looking into the API I will get to use to make my plugin compatible with Autoptimize.

**Comment by futtta** [comment]
OK, stupid bug in the code I provided; the return statement used an non-existent variable (`$dontmoveIn` iso `sdontmove_array`). Pretty sure I was high on chlorine of our holiday swimming pool ;-)

Below code was tested and does work;

```php
add_filter('autoptimize_filter_js_dontmove','remzi_noptimize');
function remzi_noptimize( $dontmove_array ) {
  $dontmove_array[] = '/jquery-manager/assets/js';
  return $dontmove_array;
}
```

Have fun Remzi! :-)

**Comment by Remzi1993** [comment]
Hi @futtta 

Thank you for your example! 👍  I will check this out tomorrow. I will let you know if this works.

Kind regards,
Remzi

**Comment by Remzi1993** [comment]
Hi @futtta 

I have resolved this issue and added support for Autoptimize.
Thank you for your support.

Kind regards,
Remzi

**Comment by futtta** [comment]
happy to help Remzi :)
