### ISSUE TITLE
JQuery UI 1.11.4

### ISSUE THREAD

**Issue by max23468** [Remzi1993/wp-jquery-manager#46]
Thank's to your plugin I've fixed two errors in Google LightHouse about JQuery vulnerabilites, but still there's another one about jQuery UI 1.11.4

It's possible to update it too with the plugin?

**Comment by Remzi1993** [comment]
I'm very sorry for my late reaction. I really don't have the time anymore to do this.
This plugin is only for jQuery and jQuery Migrate. If you're able to code (PHP and some basic understanding of some WordPress API's) than maybe you could implement this yourself and at it to the plugin.
