### ISSUE TITLE
Can't Activate

### ISSUE THREAD

**Issue by rsmith4321** [Remzi1993/wp-jquery-manager#6]
If I try to activate the plugin I get the following error. 

Warning: require(/srv/users/ryansmithphotography/apps/ryansmithphotography/public/wp-content/plugins/wp-jquery-manager-master/inc/plugin-update-checker/plugin-update-checker.php): failed to open stream: No such file or directory in /srv/users/ryansmithphotography/apps/ryansmithphotography/public/wp-content/plugins/wp-jquery-manager-master/wp-jquery-manager.php on line 55

**Comment by Remzi1993** [comment]
Hi @rsmith4321,

You should download the complied .zip file. [Download jQuery Manager v1.7.1](https://github.com/Remzi1993/wp-jquery-manager/releases/download/1.7.1/wp-jquery-manager.zip)

Please, go to the [releases](https://github.com/Remzi1993/wp-jquery-manager/releases) page to download a compiled/packaged .zip file.

Let me know if you need anything else

King Regards,
Remzi
