### ISSUE TITLE
Page taking too long to open when plugin is activated

### ISSUE THREAD

**Issue by Mancunia** [Remzi1993/wp-jquery-manager#61]
I'm lazy and want others to work harder for nothing. And I'm very entitled and don't understand that most open source projects are run as a hobby and/or for free. (Edit: fixed it for you)

**Comment by Remzi1993** [comment]
Hi @Mancunia 

You're not giving me a lot of information. Please provide me with more info, for example WP version, PHP version and how long?
I can't investigate further if you just post something without any information/clarification.

Kind regards,
Remzi

**Comment by Remzi1993** [comment]
I'm closing this issue because lack of information and complete nonsense.
