### ISSUE TITLE
Update to latest release of jQuery

### ISSUE THREAD

**Issue by mrEckendonk** [Remzi1993/wp-jquery-manager#7]
Hi,

Would be nice if you keep track of the latest releases of https://github.com/jquery/jquery/releases and have these in the plugin. Current at time of writing is version 3.4.1

**Comment by Remzi1993** [comment]
Will do! I will update my WP plugin in the coming days.
@Eckybrazzz Thank you for the heads up.

**Comment by Remzi1993** [comment]
Hi @Eckybrazzz I have updated my WP plugin.
